name: Issue Check
on:
    issues: 
        types: opened
jobs:
    check_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Run Node.js Script
              run: |
                echo $(ls)

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}