name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"
                if jq empty <<< "${{ github.event.issue.body }}" 2>/dev/null
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Found valid JSON schema"
                else
                    gh issue comment ${{ github.event.issue.html_url }} --body "Found invalid JSON schema"
                    gh issue close ${{ github.event.issue.html_url }}
                fi

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}