name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"

                TITLE=$(echo "$JSON" | jq -r '.name')
                AUTHOR=$(echo "$JSON" | jq -r '.author')

                if "$TITLE" == "null" || "$AUTHOR" == "null"
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Missing title or author"
                    gh issue close ${{ github.event.issue.html_url }}
                    exit 
                fi

                METADATA=$(echo "$JSON" | jq -r '.metadata')
                if "$METADATA" != "null" && jq -e . jq -e . >/dev/null 2>&1 <<< "$JSON"
                then
                    MSG=$(cat <<< END >>>
                        METADATA RETRIEVED!
                        TITLE: $TITLE
                        AUTHOR: $AUTHOR
                    END)
                    gh issue comment ${{ github.event.issue.html_url }} --body $MSG
                    gh issue close ${{ github.event.issue.html_url }}
                else
                    gh issue comment ${{ github.event.issue.html_url }} --body Invalid JSON metadata
                    gh issue close ${{ github.event.issue.html_url }}
                    exit
                fi

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    JSON: ${{ github.event.issue.body }}