name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"

                gh issue comment ${{ github.event.issue.html_url }} --body "Your issue will be processed shortly"

                TITLE=$(echo "$JSON" | jq -r '.name')
                AUTHOR=$(echo "$JSON" | jq -r '.author')
                DESCRIPTION=$(echo "$JSON" | jq -r '.author')
                VERSION=$(echo "$JSON" | jq -r '.author')
                METADATA=$(echo "$JSON" | jq -r '.metadata')

                if "$TITLE" == "null" || "$AUTHOR" == "null" || "$METADATA" == "null" || "$DESCRIPTION" == "null" || "$VERSION" == "null"
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Missing metadata attributes"
                    gh issue close ${{ github.event.issue.html_url }}
                    exit 
                fi

                if jq -e . >/dev/null 2>&1 <<< "$METADATA"
                then
                    FILE_NAME="$AUTHOR.$TITLE.json"
                    ENCODED_DATA=$(echo "$JSON" | base64 -w0)
                    FULL_FILE_PATH="repos/${{ github.repository }}/contents/themes/$FILE_NAME"
                    MESSAGE='{"message":"New Theme","content":"'$ENCODED_DATA'","branch":"${{ github.ref_name }}"}'

                    echo hi
                    gh issue comment ${{ github.event.issue.html_url }} --body "
                    METADATA RETRIEVED!
                    TITLE: $TITLE
                    DESCRIPTION: $DESCRIPTION
                    AUTHOR: $AUTHOR
                    VERSION: $VERSION
                    CREATING FILE IN THEMES FOLDER CALLED $FILE_NAME ($FULL_FILE_PATH)"
                    
                    echo $MESSAGE
                    
                    gh api --method PUT "$FULL_FILE_PATH" \
                        --header "Accept: application/vnd.github.v3+json" \
                        --input <(echo $MESSAGE)

                    gh issue comment ${{ github.event.issue.html_url }} --body "CREATED! CLOSING ISSUE"
                    gh issue close ${{ github.event.issue.html_url }}
                else
                    gh issue comment ${{ github.event.issue.html_url }} --body "Invalid JSON metadata"
                    gh issue close ${{ github.event.issue.html_url }}
                    exit
                fi

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    JSON: ${{ github.event.issue.body }}