name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"
                body=$(gh issue view ${{ github.event.issue.html_url }} --json body --jq 'body')
                
                echo "Found body $body"

                gh issue close ${{ github.event.issue.html_url }}
                if ! [ "$body" != "https://*" ]
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Invalid URL given, exiting early"
                    exit
                fi
                json=$(curl -sSL "$body")
                gh issue comment ${{ github.event.issue.html_url }} --body "DATA: $body"

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}