name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"                
                echo "hi"
                
                name=$(echo "${{ env.JSON }}" | jq -r '.name')
                author=$(echo "${{ env.JSON }}" | jq -r '.author')

                echo "hi"

                if "$name" == "null" || "$author" == "null"
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Missing title or author"
                    gh issue close ${{ github.event.issue.html_url }}
                    exit 
                fi

                gh issue comment ${{ github.event.issue.html_url }} --body "Name: $name\nAuthor: $author"                    

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    JSON: ${{ github.event.issue.body }}