name: Issue Check
on:
    issues: 
        types: opened
jobs:
    issue_check:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Found issue ${{ github.event.issue.number }}"                

                JSON='${{ env.JSON }}'

                TITLE=$(echo "$JSON" | jq -r '.name')
                AUTHOR=$(echo "$JSON" | jq -r '.author')

                if "$TITLE" == "null" || "$AUTHOR" == "null"
                then
                    gh issue comment ${{ github.event.issue.html_url }} --body "Missing title or author"
                    gh issue close ${{ github.event.issue.html_url }}
                    exit 
                fi

                gh issue comment ${{ github.event.issue.html_url }} --body "Name: $TITLE\nAuthor: $AUTHOR"                    

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    JSON: ${{ github.event.issue.body }}